site_name: Canto tutorial

theme:
  name: material
  logo: assets/canto_logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - content.action.edit
    - navigation.expand

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences


extra_css:
  - stylesheets/extra.css

plugins:
  - search

repo_url: https://github.com/pombase/canto_tutorial
site_url: https://pombase.github.io/canto_tutorial/
edit_uri: edit/master/docs/

extra:
  generator: false

nav:
  - Home: index.md
  - Genes, alleles and genotypes: genes_alleles_genotypes.md
  - How to annotate:
    - GO Biological Process: go_BP.md
    - GO Cellular Component: go_CC.md
    - GO Molecular Function: go_MF.md
    - Phenotypes: phenotypes.md
    - Physical Interaction: physical_interaction.md
    - Genetic Interaction: genetic_interaction.md
    - Protein modification: protein_modification.md
    - Protein sequence feature/motif: protein_sequence_feature.md
    - RNA or protein level: rna_protein_level.md
  - Other:
    - Introduction to annotation: intro_annotation.md
    - Requesting to curate a paper: request_curation_session.md
    - Productivity tricks: productivity.md