site_name: Canto tutorial

theme:
  name: material
  logo: assets/canto_logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.instant


extra_css:
  - stylesheets/extra.css

plugins:
  - search

repo_url: https://github.com/pombase/canto_tutorial
site_url: https://pombase.github.io/canto_tutorial/
edit_uri: edit/master/docs/

extra:
  generator: false