site_name: Canto tutorial

theme:
  name: material
  logo: assets/canto_logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - content.action.edit



extra_css:
  - stylesheets/extra.css

plugins:
  - search

repo_url: https://github.com/pombase/canto_tutorial
site_url: https://pombase.github.io/canto_tutorial/
edit_uri: edit/master/docs/

extra:
  generator: false

nav:
  - Home: index.md
  - Genes, alleles and genotypes: genes_alleles_genotypes.md
  - Requesting to curate a paper: request_curation_session.md