site_name: Canto tutorial

theme:
  name: material
  logo: assets/canto_logo.svg
  favicon: assets/favicon.ico
  features:
    # This messed up the custom footer
    # - navigation.instant
    - content.action.edit
    - navigation.expand

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list



extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/extra.js

plugins:
  - search
  - macros

repo_url: https://github.com/pombase/canto_tutorial
site_url: https://pombase.github.io/canto_tutorial/
edit_uri: edit/master/docs/

extra:
  generator: false

nav:
  - Home: index.md
  - How to annotate:
    - Genotype management: genotype_management.md
    - Phenotypes: phenotypes.md
    - Genetic Interaction: genetic_interaction.md
    - Physical Interaction: physical_interaction.md
    - Protein modification: protein_modification.md
    - Protein sequence feature/motif: protein_sequence_feature.md
    - Wild-type RNA or protein level: rna_protein_level.md
    - GO Molecular Function: go_MF.md
    - GO Biological Process: go_BP.md
    - GO Cellular Component: go_CC.md
  - Other:
    - Requesting to curate a paper: request_curation_session.md
    - Productivity tricks: productivity.md
    - Describing alleles: describing_alleles.md
  - FAQs: faqs.md